In [58]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [59]:
df = pd.read_csv("./data/data.csv")
df.head()
df = df.drop(["index", "price", "sq_price"], axis=1)

In [60]:
df.head()

area  bathrooms
0  2104.0        3.0
1  1600.0        3.0
2  2400.0        3.0
3  1416.0        2.0
4  3000.0        4.0

In [61]:
df = df[0:10]
df.loc[:, ("y1")] = [1,1,0,0,0,1,1,1,0,1] # 1 = good, - = bad
df.loc[:, ("y2")] = df['y1'] == 0 # y2 is exact opposite of y1
df.loc[:, "y2"] = df["y2"].astype(int)
df

area  bathrooms  y1  y2
0  2104.0        3.0   1   0
1  1600.0        3.0   1   0
2  2400.0        3.0   0   1
3  1416.0        2.0   0   1
4  3000.0        4.0   0   1
5  1985.0        4.0   1   0
6  1534.0        3.0   1   0
7  1427.0        3.0   1   0
8  1380.0        3.0   0   1
9  1494.0        3.0   1   0

In [62]:
X = df.loc[:, ['area', 'bathrooms']].as_matrix()
y = df.loc[:, ['y1', "y2"]].as_matrix()

In [63]:
X

array([[  2.10400000e+03,   3.00000000e+00],
       [  1.60000000e+03,   3.00000000e+00],
       [  2.40000000e+03,   3.00000000e+00],
       [  1.41600000e+03,   2.00000000e+00],
       [  3.00000000e+03,   4.00000000e+00],
       [  1.98500000e+03,   4.00000000e+00],
       [  1.53400000e+03,   3.00000000e+00],
       [  1.42700000e+03,   3.00000000e+00],
       [  1.38000000e+03,   3.00000000e+00],
       [  1.49400000e+03,   3.00000000e+00]])

In [64]:
y

array([[1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [1, 0]])

In [65]:
#parameters
learningRate = 0.00001
training_epochs = 2000
dislay_step = 50
n_samples = y.size

In [66]:
x = tf.placeholder(tf.float32, [None, 2])
W = tf.Variable(tf.zeros([2,2])) #Number of input features, number of output classes
b = tf.Variable(tf.zeros([2]))
y_values = tf.add(tf.matmul(x, W), b)
y_pred = tf.nn.softmax(y_values)

y_ = tf.placeholder(tf.float32, [None,2])

In [67]:
cost = tf.reduce_mean(tf.pow(y_ - y_pred,2))/ (2*n_samples)
optimizer = tf.train.GradientDescentOptimizer(learningRate).minimize(cost)

In [68]:
init = tf.global_variables_initializer()
sess = tf.InteractiveSession()
sess.run(init)

In [69]:
#Train the model

for i in range(training_epochs):
    sess.run(optimizer, feed_dict={x: X, y_: y})
    if i % 10 == 0:
        cc = sess.run(cost, feed_dict={x: X, y_: y})
        print("training step:", '%04d' % (i), "Cost=", "{:,.9f}".format(cc))

print("Optimization finished")
training_cost = sess.run(cost, feed_dict={x: X, y_: y})
print("Training cost:", training_cost, "W=", sess.run(W), "b=", sess.run(b))

('training step:', '0000', 'Cost=', '0.006223696')
('training step:', '0010', 'Cost=', '0.006183183')
('training step:', '0020', 'Cost=', '0.006182813')
('training step:', '0030', 'Cost=', '0.006182808')
('training step:', '0040', 'Cost=', '0.006182807')
('training step:', '0050', 'Cost=', '0.006182806')
('training step:', '0060', 'Cost=', '0.006182804')
('training step:', '0070', 'Cost=', '0.006182804')
('training step:', '0080', 'Cost=', '0.006182802')
('training step:', '0090', 'Cost=', '0.006182801')
('training step:', '0100', 'Cost=', '0.006182800')
('training step:', '0110', 'Cost=', '0.006182798')
('training step:', '0120', 'Cost=', '0.006182797')
('training step:', '0130', 'Cost=', '0.006182796')
('training step:', '0140', 'Cost=', '0.006182794')
('training step:', '0150', 'Cost=', '0.006182794')
('training step:', '0160', 'Cost=', '0.006182793')
('training step:', '0170', 'Cost=', '0.006182791')
('training step:', '0180', 'Cost=', '0.006182790')
('training step:', '0190', 'Cos

In [70]:
sess.run(y_pred, feed_dict={x: X})

array([[ 0.55885255,  0.44114748],
       [ 0.54486078,  0.45513925],
       [ 0.56702805,  0.43297198],
       [ 0.53971022,  0.46028981],
       [ 0.58350706,  0.41649291],
       [ 0.5555799 ,  0.44442007],
       [ 0.54302275,  0.45697722],
       [ 0.54004049,  0.45995948],
       [ 0.53872961,  0.46127036],
       [ 0.54190826,  0.45809177]], dtype=float32)